### ISSUE TITLE
Error is raised on returning to session 

### ISSUE THREAD

**Issue by jpmens** [ckrey/MQTTInspector#35]
Error is raised on returning to session

Steps to reproduce:
1. Connect to session.
2. Press SUB on one or more pre-defined SUBs
3. Return to session list
4. Click on session:

`MQTTInspector Error: Domain=NSOSStatusErrorDomin Code=-9806 "The operation couldn't be completed. (OSStatus error -9806.)"`

A click on Connect then successfully connects.

**Comment by bacancy** [comment]
i am trying to connect server by enabling SSL option to YES then i got 'CFNetwork SSLHandshake failed (-9806)' this error and if i set SSL to NO then i didn't receive anything, none of delegate method called.

**Comment by jpmens** [comment]
I think you should open this as an issue on the MQTTClient issue tracker.

**Comment by ckrey** [comment]
@bacancy please raise an issue here : https://github.com/ckrey/MQTT-Client-Framework/issues

and add some detail of the broker, version and configuration you use
