### ISSUE TITLE
Not connecting to RPi

### ISSUE THREAD

**Issue by alport** [ckrey/MQTTInspector#60]
Hi,
My MQTTInspector 1.6 won't connect to any of my RPi's. It was working about a month ago - don't remember what version, but now it won't connect to any of my 3x RPI's - all running V3.1 Mosquitto broker. 
Some other info:
1. It doesn't connect on both my IPad or iPhone6.
2. I can connect to the RPi's using MQTTfx and Chrome Lens on my laptop, and also using MQTT Tester on my iPad.
3. I can subscribe and publish to the demo eclipse.org and mosquito.org.
The screen just shows a blue "Connect" which should go grey when it connects and the "Disconnect" should turn blue - it never does.
Everything points to a problem with the iOS MQTTInspector and RPi combination.
I would like to get it running again because I found MQTTInspector to be the best of all the clients available. (Also, I have just got a bunch of ESP's!)
Any ideas?
Thanks,
Mike Alport

**Comment by ckrey** [comment]
Hi Mike,

you may have upgraded to version 1.6 of MQTT Inspector since you last used it.

If you are using the setup you created in previous version, the default for `Protocol Level`may be incorrect.

Please have a look at the configuration for your brokers and check if a Protocol level is specified and if it is the correct one (either 3 for MQTT 3.1 or 4 for MQTT 3.1.1).

Sorry for the inconvenience.
   Christoph

**Comment by alport** [comment]
Hi Christopher,
Spot on.
You diagnosed the problem and gave the correct solution.
It was driving me mad😅

Thanks,
Mike

On Monday, April 20, 2015, Christoph Krey <notifications@github.com> wrote:

> Hi Mike,
>
> you may have upgraded to version 1.6 of MQTT Inspector since you last used
> it.
>
> If you are using the setup you created in previous version, the default
> for Protocol Levelmay be incorrect.
>
> Please have a look at the configuration for your brokers and check if a
> Protocol level is specified and if it is the correct one (either 3 for MQTT
> 3.1 or 4 for MQTT 3.1.1).
>
> Sorry for the inconvenience.
> Christoph
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ckrey/MQTTInspector/issues/60#issuecomment-94535472>.
>


-- 
Dr Mike Alport (PhD Iowa)
Managing Director
Advanced Imaging Technologies (Pty) Ltd
Unit 20, 8 Reed Place, Maxmead, Pinetown, 3610, South Africa.
PO Box 906, Westville, 3630, South Africa.
Ph: +27 (0)31 701-7078
Fax:+27 (0)86 510-2225
Cell:+27 (0)82 555-1747
Email: alport@ait-sa.com
URL: www.AIT-SA.com
Skype: mike.alport
