### ISSUE TITLE
MQTTSession delegate method not called

### ISSUE THREAD

**Issue by bacancy** [ckrey/MQTTInspector#61]
i am trying to connect server using #MQTTClient-Framework by enabling SSL option to YES then i got 'CFNetwork SSL Handshake failed (-9806)' this error and if i set SSL to NO then i didn't receive anything, none of delegate method called.

**Comment by ckrey** [comment]
@bacancy please raise an issue here : https://github.com/ckrey/MQTT-Client-Framework/issues

and add some detail of the broker, version and configuration you use
