### ISSUE TITLE
Crash on disconnect

### ISSUE THREAD

**Issue by jpmens** [ckrey/MQTTInspector#63]
Create a TLS profile with one subscription in it (redline)
Connect. See messages.
Hit `Disconnect`: crash.

iPad2 with iOS9

**Comment by ckrey** [comment]
Thanks, found the problem.

It is an UI problem, not related to MQTT. To work around the problem until a new version is available in the app store, Don't close the connection via the 'x' button, but navigate back to the broker selection list.

**Comment by jpmens** [comment]
Fine, thanks -- no problem, and no hurry.
