### ISSUE TITLE
When will v2 be on App store?

### ISSUE THREAD

**Issue by d0dja** [ckrey/MQTTInspector#69]
Hi Christoph - really value what you've been doing here with MQTTinspector -- but really wanting to get V2 (if it's more stable).

Using it regularly as a critical tool in an R&D project, but the lack of stability is driving me nuts.

Also -- what would be REALLY useful is a "leave running in background" so that I can leave it watching a topic. Right now, I have to sit and prod the screen every minute or two to stop the phone sleeping, at which point app closes and it loses everything (disabling sleep on the phone is not a useful workaround).

**Comment by ckrey** [comment]
v2 will be in the store in February, promised.

I see the problems re stability, which causes the app to start from scratch when activated again. This problem is solved. So with 2.0 you will find yourself on the same screen as when you locked your phone. If you combine this with "autoconect=ON" an "cleansession=OFF", I think you'll get what you are looking for.

On the other hand: there is no "leave running in the background" in iOS. What I could do is implement a "monitor" mode which disables the autolock (=sleep) while the app is active.

Any feedback is welcome!

**Comment by d0dja** [comment]
Hey thanks for the super quick response.

We’re using MQTTinspector to build a prototype  massively distributed real-time spectrum characterisation and occupancy sensing system. Which will Change The World.

A “monitor” mode would be cool. The prob with toggling the phone’s autolock feature is that you forget to change it back, and boom battery dead.

Perhaps also a “log” mode, that writes messages to an archive so that one could copy it off later for further study?

But thanks for your work on this… the Internet community at its best.

Cheers
Roger

On 29/01/2016 11:53, "Christoph Krey" <notifications@github.com<mailto:notifications@github.com>> wrote:


v2 will be in the store in February, promised.

I see the problems re stability, which causes the app to start from scratch when activated again. This problem is solved. So with 2.0 you will find yourself on the same screen as when you locked your phone. If you combine this with "autoconect=ON" an "cleansession=OFF", I think you'll get what you are looking for.

On the other hand: there is no "leave running in the background" in iOS. What I could do is implement a "monitor" mode which disables the autolock (=sleep) while the app is active.

Any feedback is welcome!

**Comment by ckrey** [comment]
entered separate enhancement issues #70 and #71

**Comment by ckrey** [comment]
@d0dja if you share an email address with me, I will invite you to be a beta tester for 2.0.x

**Comment by d0dja** [comment]
I’m roger.hislop@is.co.za.

I’ll delete this post soon as I get a mail from you.

~R


On 31/01/2016 07:50, "Christoph Krey" <notifications@github.com<mailto:notifications@github.com>> wrote:


@d0dja<https://github.com/d0dja> if you share an email address with me, I will invite you to be a beta tester for 2.0.x
