### ISSUE TITLE
“log” mode

### ISSUE THREAD

**Issue by ckrey** [ckrey/MQTTInspector#71]
Perhaps also a “log” mode, that writes messages to an archive so that one could copy it off later for further study?

**Comment by ckrey** [comment]
In the early days such a functionality was included.
IMHO the iDevice is not actually the right type of device for archiving / storing / further study.

I would recommend to setup a log with the broker or at another machine running e.g. mosquitto_sub

**Comment by jpmens** [comment]
IMO this feature would be overkill for the Inspector. As you rightly say, a simple subscriber which dumps topics and data into a file or database is much better suited. Furthermore, if a logging feature is implemented, you have to think about how to transport that log *out* of the iOS device, data formats, etc. Sounds like creaping featurism. ;-)
