### ISSUE TITLE
Flip portrait/landscape

### ISSUE THREAD

**Issue by jpmens** [ckrey/MQTTInspector#72]
When I flip the iPad from landscape to portrait or vice versa, the result is like shown. Please note: I mention this FYI only; I''m quite sure we can all live with this. (Version: latest testflight.)

![image](https://cloud.githubusercontent.com/assets/60706/12703801/f719a15c-c84b-11e5-83c7-ed39ed7d6069.png)

**Comment by jpmens** [comment]
Long press on the Topics pane redraws the screen fine.

**Comment by ckrey** [comment]
Fixed
