### ISSUE TITLE
Add separator between topic and value

### ISSUE THREAD

**Issue by tedenda** [ckrey/MQTTInspector#78]
I think it would be good if there is some separator between topic and value.
Examples:
/garage/co2 = 116
/garage/co2:116
/garage/co2-->116

![img_0213](https://cloud.githubusercontent.com/assets/4216986/13196975/a340569a-d7df-11e5-8f5c-03009c4d3839.jpg)

**Comment by ckrey** [comment]
Thanks for your comment. I already addressed this point for the next version.

**Comment by tedenda** [comment]
Perfect!
