### ISSUE TITLE
Add additional MQTT brokers

### ISSUE THREAD

**Issue by dobermai** [ckrey/MQTTInspector#79]
It would be great to add additional pre-configured MQTT brokers. A list of available public MQTT brokers is available here:

http://moxd.io/2015/10/public-mqtt-brokers/

**Comment by ckrey** [comment]
Hallo Dominik,

klar, ist in der nächsten Version drin.

Christoph

**Comment by jpmens** [comment]
`broker.hivemq.com` == `broker.mqttdashboard.com` (same A record); I'd add one of those only, maybe the latter so as to avoid _advertisement_ (with all due repect to @dobermai of course! :smile: )
