### ISSUE TITLE
cant connect with mosquitto,org or others

### ISSUE THREAD

**Issue by svtgd** [ckrey/MQTTInspector#80]
Im new to MQTT and just got the MQTTInspector IOS app - and not having much luck. When I first open the app, a window pops up w/  MQTTSessionEventConnectionError (3) Error Domain=NSPOSIXErrorDomainCode=54 "Connection reset by peer".

I can connect to included eclipse.org session , but when I try to connect to the included mosquitto.org session, I get the same errors. MQTTSessionEventConnectionError (3) Error Domain=NSPOSIXErrorDomainCode=54 "Connection reset by peer". 

I created a session to cloudmqtt.com, but am getting the same errors. I was able to create a working connection to this cloudMQTT in android app MQTT Dashboard,  so I know the connection info I used there worked.....

Is there any doc for the app? I found a video, but it uses mosquitto.org - which I cant connect to, and doesn't cover the settings for a new session. 

Any help is appreciated. Hank

**Comment by ckrey** [comment]
I can easily connect to mosquitto.org.

Is your error persistent?
