### ISSUE TITLE
PUB Icons in Notification Center

### ISSUE THREAD

**Issue by syoma755** [ckrey/MQTTInspector#81]
Hello,
I'm looking for MQTT iOS tool which would be useful for my house automation. 
What I need, is ability to have icons in iOS Notification Center, which, being tapped would establish connection to MQTT Broker and publish some message. 
Is it possible to implement? That would be the best remote control app.

**Comment by ckrey** [comment]
Not in the notification center, but in the Today app where you see weather, reminders, calendar, etc.
No problem

**Comment by syoma755** [comment]
So any progress on this?

**Comment by ckrey** [comment]
I will pick this up and may even do some more similar to https://play.google.com/store/apps/details?id=net.routix.mqttdash

Maybe I will add this the MQTTInspector or I will spin off a new app called MQTTCommander?

**Comment by ckrey** [comment]
MQTTInspector will not become a Remote Control App
