### ISSUE TITLE
AWS IoT Client Certificate Usage

### ISSUE THREAD

**Issue by bombadil67** [ckrey/MQTTInspector#87]
Having the impression that MQTTInspector can deal with client certificates as required by AWS IoT broker, I've found no way to select them in the (currently empty) list of certificates.

What I did was to mail an encrypted .p12 to myself, and I've added it as profile. Was that the right thing to do? Is there any docuementation on how to achieve this? I know that owntracks can do this, but I now wanted the more versatile MQTTInspector for subscribing to the broker.

I'm currently on iOS 13.1.1.
Thanks!

**Comment by rlodge** [comment]
I don’t see MQTTInspector as an option to open the file.

**Comment by bombadil67** [comment]
I got it working by emailing myself the PKCS12 file as xyz.p12.mqtc . I then started MQTTInspector, selected the attachment in mail and used share -> more -> Copy to MQTTInspector.
When having done this, the certificate was available under Client Certificates as Christoph described.

Thanks @ckrey , MQTTInspector works like a charm now with AWS !
