### ISSUE TITLE
UI: Red new message indications a bit misleading 

### ISSUE THREAD

**Issue by bombadil67** [ckrey/MQTTInspector#88]
I'm receiving messages from multiple publishers, all data is displayed well. However, I'm receiving 1 message per publisher per second. Each of the received topics (in topic display grouping mode) is marked by a red ba when a new message arrives; good. However, each received message is marked 4 times with this red bar as if it would receive 4 messages. Can you/we change that to one time per received message?

Also: I received data from 25 publishers, so the list needed scrolling. After having unsubscribed  from any topic, I scrolled down this topic-grouped message list, and I still received those red bars  for the previously non-visible elements (minor UI glitch I think).

@ckrey : Otherwise perfect!

**Comment by ckrey** [comment]
Released with 13.1.4 (in iOS 13)
