### ISSUE TITLE
Self-signed certificate not recognized

### ISSUE THREAD

**Issue by tedstriker** [ckrey/MQTTInspector#89]
Since iOS Update to 13.3 (from 12.x) the self-signed root certificate which has been added to trusted certificates on iPhone and iPad is not recognized anymore.
No error is shown, but no connection is established until the option "Allow untrusted certificates" is activated.

**Comment by ckrey** [comment]
Yes, Apple changed the requirements for trusted certificates.
You may upgrade the certificates as explained in owntracks/ios#612

**Comment by tedstriker** [comment]
Thank you for pointing out the changed policies. Adjusting properties of the certificate did the trick.
